### ISSUE TITLE
CUDA error: uncorrectable ECC error encountered

### ISSUE THREAD

**Issue by rveltz** [JuliaGPU/CUDAdrv.jl#106]
Hi,

I am having the following issue and I have no clue how to fix it... 

I would appreciate any help,.

Thank you,

Best regards

Romain

```julia
julia> Pkg.test("CUDAdrv")
INFO: Testing CUDAdrv
INFO: Testing using device Tesla K80
CUDAdrv: Error During Test
  Got an exception of type CUDAdrv.CuError outside of a @test
  CUDA error: uncorrectable ECC error encountered (code #214, ERROR_ECC_UNCORRECTABLE)
  Stacktrace:
   [1] macro expansion at /home/rveltz/.julia/v0.6/CUDAdrv/src/base.jl:148 [inlined]
   [2] CUDAdrv.CuContext(::CUDAdrv.CuDevice, ::CUDAdrv.CUctx_flags) at /home/rveltz/.julia/v0.6/CUDAdrv/src/context.jl:118
   [3] macro expansion at /home/rveltz/.julia/v0.6/CUDAdrv/test/runtests.jl:23 [inlined]
   [4] macro expansion at ./test.jl:860 [inlined]
   [5] anonymous at ./<missing>:?
   [6] include_from_node1(::String) at ./loading.jl:576
   [7] include(::String) at ./sysimg.jl:14
   [8] process_options(::Base.JLOptions) at ./client.jl:305
   [9] _start() at ./client.jl:371
Test Summary: | Pass  Error  Total
CUDAdrv       |    9      1     10
  base        |    5             5
ERROR: LoadError: Some tests did not pass: 9 passed, 0 failed, 1 errored, 0 broken.
while loading /home/rveltz/.julia/v0.6/CUDAdrv/test/runtests.jl, in expression starting on line 6
===================================================[ ERROR: CUDAdrv ]====================================================

failed process: Process(`/home/rveltz/build/julia/usr/bin/julia -Cnative -J/home/rveltz/build/julia/usr/lib/julia/sys.so --compile=yes --depwarn=yes --check-bounds=yes --code-coverage=none --color=yes --compilecache=yes /home/rveltz/.julia/v0.6/CUDAdrv/test/runtests.jl`, ProcessExited(1)) [1]

=========================================================================================================================
ERROR: CUDAdrv had test errors
```

**Comment by rveltz** [comment]
Seems to be hardware related. Reinstalling everything solved the issue.

**Comment by HebaGamalElDin** [comment]
> Seems to be hardware related. Reinstalling everything solved the issue.

reinstalling everything referees to what?!
work environment (e.g anaconda) or installing the OS?
I'm facing the same error (""CUDA error: uncorrectable ECC error encountered "") while train a network in Pytorch Cuda enabled.

**Comment by Tomlac92** [comment]
I had similar problem (CUDA error code 214), I did close spyder during train the Pytorch model (storm with thunders arrived, so I had to hurry). In effect memory of my device become blocked and restarting the kernel, even restarting the computer, disconnecting gpu from MOBO and connecting again didn't help. I solved it by device manager (Windows10) - right click and disconnect device and connect back without reboting PC.
